"""initial config

Revision ID: 16201bbd29dc
Revises: 
Create Date: 2024-10-27 21:13:35.342665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16201bbd29dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id_purchase', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_address', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_purchase'),
    schema='ms_purchases'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases', schema='ms_purchases')
    # ### end Alembic commands ###
